# ==============================================================================
# NieR:Automata YoRHa UI Theme 
# ==============================================================================
allow_remote_control yes
listen_on unix:/tmp/kitty-yorha

background            #c8c2aa
foreground            #1a1714
selection_background  #1a1714
selection_foreground  #c8c2aa
url_color             #3a2e1e

window_padding_width  15

draw_minimal_borders   yes
window_border_width     2.0pt
hide_window_decorations no
active_border_color     #1a1714
inactive_border_color   #8a8470

font_family          Noto Sans Mono
bold_font            Noto Sans Mono Bold
font_size            11.0

adjust_column_width  110%

repaint_delay    2
input_delay      0
sync_to_monitor  yes

# ------------------------------------------------------------------------------
cursor                #1a1714
cursor_text_color     #c8c2aa
cursor_shape          block
cursor_blink_interval 0.4

cursor_trail          3
cursor_trail_decay    0.1 0.4

enable_audio_bell     no
visual_bell_duration  0.15
visual_bell_color     #a34b43 
window_alert_on_bell  yes

tab_bar_style           separator
tab_separator           " ❘ "
tab_activity_symbol     "⌁ " 

active_tab_background   #4d493e
active_tab_foreground   #c8c2aa
inactive_tab_background #b8b29a
inactive_tab_foreground #4d493e

color0  #1a1714
color8  #2e2b24

color1  #6b1e18
color9  #521510

color2  #354428
color10 #263318

color3  #4a4638
color11 #383522

color4  #2a3e4d
color12 #1a2a36

color5  #4a3040
color13 #361e2c

color6  #2a4a46
color14 #1c3330

color7  #1a1714
color15 #0d0c0a
