# ==============================================================================
# NieR:Automata YoRHa UI Theme - Dark
# ==============================================================================
allow_remote_control yes
listen_on unix:/tmp/kitty-yorha
shell $HOME/.config/hypr/themes/yorha/components/kitty/startup.sh

background            #57544a
foreground            #dad4bb
selection_background  #dad4bb
selection_foreground  #413d34
url_color             #f4f0e1

window_padding_width  15

draw_minimal_borders   yes
window_border_width     2.0pt
hide_window_decorations no
active_border_color     #dad4bb
inactive_border_color   #8a8470

font_family          Noto Sans Mono
bold_font            Noto Sans Mono Bold
font_size            11.0

adjust_column_width  110%

repaint_delay    2
input_delay      0
sync_to_monitor  yes

# ------------------------------------------------------------------------------
cursor                #dad4bb
cursor_text_color     #413d34
cursor_shape          block
cursor_blink_interval 0.4

cursor_trail          3
cursor_trail_decay    0.1 0.4

enable_audio_bell     no
visual_bell_duration  0.15
visual_bell_color     #cd664d
window_alert_on_bell  yes

tab_bar_style           separator
tab_separator           " ❘ "
tab_activity_symbol     "⌁ "  

active_tab_background   #dad4bb
active_tab_foreground   #413d34
inactive_tab_background #413d34
inactive_tab_foreground #b3ac92

color0  #17140f
color8  #413d34

color1  #cd664d
color9  #e07a61

color2  #a0c490
color10 #b8d6a8

color3  #b3ac92
color11 #dad4bb

color4  #8fa6ad
color12 #b8c9cf

color5  #b99ab0
color13 #d4bfd0

color6  #93b8b0
color14 #b7d7d0

color7  #dad4bb
color15 #f4f0e1
